### ISSUE TITLE
Batch Job is not flushing

### ISSUE THREAD

**Issue by markadrianagbuya** [gzigzigzeo/sidekiq-grouping#5]
I'm using sidekiq 3.3.3. In the readme, it says it hasn't been tested on v3 but when I implemented it, it worked perfectly on my local machine. But when I ran the batches on my staging server the jobs weren't executing. Here is the output from sidekiq:

```
2015-04-14T05:47:25.447Z 26061 TID-ot49jvtl4 INFO: [Sidekiq::Batching] Sidekiq::Batching starts supervision
2015-04-14T05:47:27.697Z 26061 TID-ot49jvtl4 INFO: Booting Sidekiq 3.3.3 with redis options {:namespace=>"ss:staging", :url=>"redis://localhost:6379"}
2015-04-14T05:47:49.484Z 26061 TID-ot49jvtl4 INFO: Running in ruby 2.0.0p481 (2014-05-08 revision 45883) [x86_64-linux]
2015-04-14T05:47:49.484Z 26061 TID-ot49jvtl4 INFO: See LICENSE and the LGPL-3.0 for licensing details.
2015-04-14T05:47:49.484Z 26061 TID-ot49jvtl4 INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org/pro
2015-04-14T05:47:49.491Z 26061 TID-ot49jvtl4 INFO: Starting processing, hit Ctrl-C to stop
2015-04-14T05:47:50.531Z 26061 TID-ot49x8bfw INFO: [Sidekiq::Batching] Start polling of queue batches every 3 seconds
2015-04-14T05:47:53.536Z 26061 TID-ot49x8bfw INFO: [Sidekiq::Batching] Trying to flush batched queues: Marketo::SynchroniseJobsBatchWorker in medium
2015-04-14T05:47:53.709Z 26061 TID-ot49x8bfw INFO: [Sidekiq::Batching] Start polling of queue batches every 3 seconds
2015-04-14T05:47:56.712Z 26061 TID-ot49x8bfw INFO: [Sidekiq::Batching] Trying to flush batched queues: Marketo::SynchroniseJobsBatchWorker in medium
2015-04-14T05:47:56.719Z 26061 TID-ot4ah463s INFO: [Sidekiq::Batching] Start polling of queue batches every 3 seconds
2015-04-14T05:47:59.723Z 26061 TID-ot4ah463s INFO: [Sidekiq::Batching] Trying to flush batched queues: Marketo::SynchroniseJobsBatchWorker in medium
2015-04-14T05:47:59.729Z 26061 TID-ot4amc2do INFO: [Sidekiq::Batching] Start polling of queue batches every 3 seconds
2015-04-14T05:48:02.732Z 26061 TID-ot4amc2do INFO: [Sidekiq::Batching] Trying to flush batched queues: Marketo::SynchroniseJobsBatchWorker in medium
2015-04-14T05:48:02.737Z 26061 TID-ot4anp86g INFO: [Sidekiq::Batching] Start polling of queue batches every 3 seconds
```

Could this be an issue to do with the `redis_pool` that is unsupported?

**Comment by markadrianagbuya** [comment]
I've determined that the above is due to an exception being raised in when trying to flush the batch. When flush the batch manually (`Sidekiq::Batching::Batch.all.first.flush`) on staging I get: 

```
Exception: Redis::CommandError: ERR unknown command 'eval'
--
 0: /data/serviceseeking_au_staging/shared/bundled_gems/ruby/2.0.0/gems/redis-3.2.1/lib/redis/client.rb:113:in `call'
 1: /data/serviceseeking_au_staging/shared/bundled_gems/ruby/2.0.0/gems/redis-3.2.1/lib/redis.rb:2277:in `block in _eval'
 2: /data/serviceseeking_au_staging/shared/bundled_gems/ruby/2.0.0/gems/redis-3.2.1/lib/redis.rb:37:in `block in synchronize'
 3: /usr/lib64/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
 4: /data/serviceseeking_au_staging/shared/bundled_gems/ruby/2.0.0/gems/redis-3.2.1/lib/redis.rb:37:in `synchronize'
 5: /data/serviceseeking_au_staging/shared/bundled_gems/ruby/2.0.0/gems/redis-3.2.1/lib/redis.rb:2276:in `_eval'
 6: /data/serviceseeking_au_staging/shared/bundled_gems/ruby/2.0.0/gems/redis-3.2.1/lib/redis.rb:2303:in `eval'
 7: /data/serviceseeking_au_staging/shared/bundled_gems/ruby/2.0.0/gems/redis-namespace-1.5.2/lib/redis/namespace.rb:393:in `call_with_namespace'
 8: /data/serviceseeking_au_staging/shared/bundled_gems/ruby/2.0.0/gems/redis-namespace-1.5.2/lib/redis/namespace.rb:283:in `eval'
 9: /data/serviceseeking_au_staging/shared/bundled_gems/ruby/2.0.0/gems/sidekiq-batching-0.0.5/lib/sidekiq/batching/redis.rb:41:in `block in pluck'
10: /data/serviceseeking_au_staging/shared/bundled_gems/ruby/2.0.0/gems/connection_pool-2.1.3/lib/connection_pool.rb:62:in `with'
11: /data/serviceseeking_au_staging/shared/bundled_gems/ruby/2.0.0/gems/sidekiq-3.3.3/lib/sidekiq.rb:74:in `redis'
12: /data/serviceseeking_au_staging/shared/bundled_gems/ruby/2.0.0/gems/sidekiq-batching-0.0.5/lib/sidekiq/batching/redis.rb:82:in `redis'
13: /data/serviceseeking_au_staging/shared/bundled_gems/ruby/2.0.0/gems/sidekiq-batching-0.0.5/lib/sidekiq/batching/redis.rb:41:in `pluck'
14: /data/serviceseeking_au_staging/shared/bundled_gems/ruby/2.0.0/gems/sidekiq-batching-0.0.5/lib/sidekiq/batching/batch.rb:35:in `pluck'
15: /data/serviceseeking_au_staging/shared/bundled_gems/ruby/2.0.0/gems/sidekiq-batching-0.0.5/lib/sidekiq/batching/batch.rb:40:in `flush'
16: (pry):7:in `__pry__'
17: /data/serviceseeking_au_staging/shared/bundled_gems/ruby/2.0.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:355:in `eval'
18: /data/serviceseeking_au_staging/shared/bundled_gems/ruby/2.0.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:355:in `evaluate_ruby'
19: /data/serviceseeking_au_staging/shared/bundled_gems/ruby/2.0.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:323:in `handle_line'
20: /data/serviceseeking_au_staging/shared/bundled_gems/ruby/2.0.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:243:in `block (2 levels) in eval'
21: /data/serviceseeking_au_staging/shared/bundled_gems/ruby/2.0.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:242:in `catch'
22: /data/serviceseeking_au_staging/shared/bundled_gems/ruby/2.0.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:242:in `block in eval'
23: /data/serviceseeking_au_staging/shared/bundled_gems/ruby/2.0.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:241:in `catch'
24: /data/serviceseeking_au_staging/shared/bundled_gems/ruby/2.0.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:241:in `eval'
25: /data/serviceseeking_au_staging/shared/bundled_gems/ruby/2.0.0/gems/pry-0.10.1/lib/pry/repl.rb:77:in `block in repl'
26: /data/serviceseeking_au_staging/shared/bundled_gems/ruby/2.0.0/gems/pry-0.10.1/lib/pry/repl.rb:67:in `loop'
27: /data/serviceseeking_au_staging/shared/bundled_gems/ruby/2.0.0/gems/pry-0.10.1/lib/pry/repl.rb:67:in `repl'
28: /data/serviceseeking_au_staging/shared/bundled_gems/ruby/2.0.0/gems/pry-0.10.1/lib/pry/repl.rb:38:in `block in start'
29: /data/serviceseeking_au_staging/shared/bundled_gems/ruby/2.0.0/gems/pry-0.10.1/lib/pry/input_lock.rb:61:in `call'
30: /data/serviceseeking_au_staging/shared/bundled_gems/ruby/2.0.0/gems/pry-0.10.1/lib/pry/input_lock.rb:61:in `__with_ownership'
31: /data/serviceseeking_au_staging/shared/bundled_gems/ruby/2.0.0/gems/pry-0.10.1/lib/pry/input_lock.rb:79:in `with_ownership'
32: /data/serviceseeking_au_staging/shared/bundled_gems/ruby/2.0.0/gems/pry-0.10.1/lib/pry/repl.rb:38:in `start'
33: /data/serviceseeking_au_staging/shared/bundled_gems/ruby/2.0.0/gems/pry-0.10.1/lib/pry/repl.rb:15:in `start'
34: /data/serviceseeking_au_staging/shared/bundled_gems/ruby/2.0.0/gems/pry-0.10.1/lib/pry/pry_class.rb:169:in `start'
35: /data/serviceseeking_au_staging/shared/bundled_gems/ruby/2.0.0/gems/railties-3.2.21/lib/rails/commands/console.rb:47:in `start'
36: /data/serviceseeking_au_staging/shared/bundled_gems/ruby/2.0.0/gems/railties-3.2.21/lib/rails/commands/console.rb:8:in `start'
37: /data/serviceseeking_au_staging/shared/bundled_gems/ruby/2.0.0/gems/railties-3.2.21/lib/rails/commands.rb:41:in `<top (required)>'
38: script/rails:39:in `require'
39: script/rails:39:in `<main>'
```

What stumps me is that it works fine on my local machine. The only difference I can see is that we configure redis on staging to have a url, with a host and port.

**Comment by gzigzigzeo** [comment]
@markadrianagbuya I think it could be redis issue. What version of redis do you use on staging? 'eval' for LUA scripting was introduced in Redis 2.6. Is your redis newer than 2.6? Are scripts enabled in your redis? Moreover, do you see anything belongs to batching in your failing/retry queue?

**Comment by gzigzigzeo** [comment]
@markadrianagbuya Could you please give me any feedback on your problem?
